site_name: LewdBot
theme:
  name: 'material'
  feature:
    tabs: true
extra_css:
  - css/extra.css
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
  - toc:
      permalink: true
nav:
    - Home: index.md
    - Features: features.md
    - List of Commands: commands.md
    - Tutorials:
      - Setup: tutorials/setup.md
      - PlayLists: tutorials/playlists.md
    - Placeholders: placeholders.md